name: 'ShokeDex Build Steps for Performance Engineering'
description: 'Validated build and test steps for performance development workflow'

runs:
  using: 'composite'
  steps:
    - name: Setup Python Environment
      shell: bash
      run: |
        echo "=== Setting up Python 3.11 environment ===" | tee -a build-steps.log
        python --version | tee -a build-steps.log
        echo "" | tee -a build-steps.log
    
    - name: Install Dependencies
      shell: bash
      run: |
        echo "=== Installing Python dependencies ===" | tee -a build-steps.log
        python -m pip install --upgrade pip 2>&1 | tee -a build-steps.log
        pip install -r requirements.txt 2>&1 | tee -a build-steps.log
        echo "" | tee -a build-steps.log
        echo "Installed packages:" | tee -a build-steps.log
        pip list 2>&1 | tee -a build-steps.log
        echo "" | tee -a build-steps.log
    
    - name: Initialize Database (if needed)
      shell: bash
      run: |
        echo "=== Checking database state ===" | tee -a build-steps.log
        if [ ! -f data/pokedex.db ]; then
          echo "Database not found, initializing..." | tee -a build-steps.log
          python src/data/manage_db.py init 2>&1 | tee -a build-steps.log
          echo "Seeding database with Gen 1-3 data (this may take 10-20 minutes)..." | tee -a build-steps.log
          python src/data/manage_db.py seed --gen 1-3 2>&1 | tee -a build-steps.log
        else
          echo "Database already exists, skipping initialization" | tee -a build-steps.log
        fi
        echo "" | tee -a build-steps.log
    
    - name: Run Unit Tests
      shell: bash
      run: |
        echo "=== Running unit tests ===" | tee -a build-steps.log
        SDL_VIDEODRIVER=dummy pytest -m unit -n auto --tb=short 2>&1 | tee -a build-steps.log
        UNIT_EXIT_CODE=$?
        echo "Unit tests exit code: $UNIT_EXIT_CODE" | tee -a build-steps.log
        echo "" | tee -a build-steps.log
        exit $UNIT_EXIT_CODE
    
    - name: Run Integration Tests
      shell: bash
      run: |
        echo "=== Running integration tests ===" | tee -a build-steps.log
        SDL_VIDEODRIVER=dummy pytest -m integration -v --tb=short 2>&1 | tee -a build-steps.log
        INTEGRATION_EXIT_CODE=$?
        echo "Integration tests exit code: $INTEGRATION_EXIT_CODE" | tee -a build-steps.log
        echo "" | tee -a build-steps.log
        exit $INTEGRATION_EXIT_CODE
    
    - name: Run Performance Tests (Optional)
      shell: bash
      continue-on-error: true
      run: |
        echo "=== Running performance tests ===" | tee -a build-steps.log
        SDL_VIDEODRIVER=dummy pytest -m performance -v 2>&1 | tee -a build-steps.log
        PERF_EXIT_CODE=$?
        echo "Performance tests exit code: $PERF_EXIT_CODE" | tee -a build-steps.log
        echo "" | tee -a build-steps.log
    
    - name: Build Summary
      shell: bash
      run: |
        echo "=== Build Steps Complete ===" | tee -a build-steps.log
        echo "Build log saved to: build-steps.log" | tee -a build-steps.log
        echo "" | tee -a build-steps.log
        echo "Next steps for performance engineering:" | tee -a build-steps.log
        echo "1. Review performance guides in .github/copilot/instructions/" | tee -a build-steps.log
        echo "2. Use tools/profile_performance.py for profiling" | tee -a build-steps.log
        echo "3. Use tools/test_input_latency.py for input testing" | tee -a build-steps.log
        echo "4. Run specific performance tests with: pytest -m performance -v" | tee -a build-steps.log
        echo "" | tee -a build-steps.log
